#!/usr/bin/env node
/**
 * Build UI-only WOFF subsets.
 *
 * Source fonts are intentionally not committed. Download the OFL-licensed files:
 * - https://github.com/google/fonts/tree/main/ofl/notoserifsc
 * - https://github.com/google/fonts/tree/main/ofl/zcoolkuaile
 * into tools/fonts-src before running `npm run subset-fonts`.
 */
import { createRequire } from 'node:module'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const Fontmin = require('fontmin')
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE_DIR = path.join(ROOT, 'tools/fonts-src')
const OUTPUT_DIR = path.join(ROOT, 'src/assets/fonts')
const MAX_TOTAL_BYTES = 1024 * 1024

const fonts = [
  {
    // Rename the Google Fonts variable file to avoid glob semantics for `[wght]`.
    input: 'NotoSerifSC.ttf',
    output: 'notoSerifSC.ts',
  },
  {
    input: 'ZCOOLKuaiLe-Regular.ttf',
    output: 'zcoolKuaiLe.ts',
  },
]

function subsetFont(input, text) {
  return new Promise((resolve, reject) => {
    new Fontmin()
      .src(input)
      .use(Fontmin.glyph({ text, hinting: false }))
      .use(Fontmin.ttf2woff())
      .run((error, files) => {
        if (error) {
          reject(error)
          return
        }
        const output = files.find(file => file.path.endsWith('.woff'))
        if (!output) {
          reject(new Error(`No WOFF output generated for ${input}`))
          return
        }
        resolve(output.contents)
      })
  })
}

async function main() {
  const text = await readFile(path.join(ROOT, 'tools/font-chars.txt'), 'utf8')
  await mkdir(OUTPUT_DIR, { recursive: true })

  let totalBytes = 0
  for (const font of fonts) {
    const input = path.join(SOURCE_DIR, font.input)
    const contents = await subsetFont(input, text)
    totalBytes += contents.length
    const dataUrl = `data:font/woff;base64,${contents.toString('base64')}`
    await writeFile(
      path.join(OUTPUT_DIR, font.output),
      `// Generated by tools/subset-fonts.mjs.\nexport default '${dataUrl}'\n`,
      'utf8',
    )
    console.log(`${font.output}: ${contents.length} bytes`)
  }

  console.log(`Total WOFF size: ${totalBytes} bytes`)
  if (totalBytes > MAX_TOTAL_BYTES) {
    throw new Error(`Font subsets exceed the 1 MB budget: ${totalBytes} bytes`)
  }
}

main().catch(error => {
  console.error(error.message)
  process.exit(1)
})
